"use client";
import Link from "next/link";
import { useEffect, useMemo, useState } from "react";

type Article={id:number;title:string;school:string;category:string;status:string;channel:string;views:number;created_at:string};
const bars=[42,55,48,69,62,77,71,88,82,96,91,100,93,116];

export default function Studio(){
 const [articles,setArticles]=useState<Article[]>([]); const [tab,setTab]=useState("Overview"); const [composer,setComposer]=useState(false); const [loading,setLoading]=useState(true);
 const [form,setForm]=useState({title:"",school:"",category:"Campus life",body:"",status:"draft",channel:"site,x"});
 async function load(){setLoading(true);const r=await fetch("/api/articles");setArticles(await r.json());setLoading(false)}
 useEffect(()=>{load()},[]);
 const views=useMemo(()=>articles.reduce((n,a)=>n+a.views,0),[articles]);
 async function save(e:React.FormEvent){e.preventDefault();await fetch("/api/articles",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(form)});setComposer(false);setForm({title:"",school:"",category:"Campus life",body:"",status:"draft",channel:"site,x"});load()}
 return <main className="studio">
  <aside><Link className="brand" href="/"><span className="seal">CP</span><span>COLLEGE<br/>PATRIOTS</span></Link><div className="workspace">EDITORIAL WORKSPACE<br/><b>NATIONAL DESK</b></div><nav>{["Overview","Articles","Analytics","Video desk","Arcade","Settings"].map(x=><button className={tab===x?"on":""} onClick={()=>setTab(x)} key={x}><span>{({Overview:"▦",Articles:"≡",Analytics:"↗","Video desk":"▶",Arcade:"✦",Settings:"⚙"} as Record<string,string>)[x]}</span>{x}</button>)}</nav><div className="studio-user"><i>JC</i><span>JORDAN CONRADSON<br/><small>MANAGING EDITOR</small></span></div></aside>
  <section className="studio-main"><header><div><span>WORKSPACE / {tab.toUpperCase()}</span><h1>{tab}</h1></div><div className="studio-actions"><button>↻ <span>SYNC CHANNELS</span></button><button className="new" onClick={()=>setComposer(true)}>＋ NEW STORY</button></div></header>
   {tab==="Overview"&&<><div className="metrics"><Metric label="TOTAL READERS" value={(views+72240).toLocaleString()} delta="+18.4%"/><Metric label="STORY VIEWS" value={views.toLocaleString()} delta="+12.1%"/><Metric label="AVG. READ TIME" value="4m 38s" delta="+6.7%"/><Metric label="SOCIAL REFERRALS" value="18.9K" delta="+24.2%"/></div><div className="studio-grid"><div className="chart panel"><div className="panel-head"><div><b>READERSHIP</b><span>LAST 14 DAYS</span></div><button>14 DAYS⌄</button></div><div className="bar-chart">{bars.map((h,i)=><i key={i} style={{height:h}}><em>{i%3===0?`${i+17} JUL`:""}</em></i>)}</div></div><div className="sources panel"><div className="panel-head"><div><b>TRAFFIC SOURCES</b><span>ALL PUBLISHED STORIES</span></div></div>{[["Direct",38,"red"],["X / Twitter",29,"blue"],["Instagram",17,"gold"],["YouTube",11,"black"],["Other",5,"gray"]].map(s=><div className="source" key={String(s[0])}><span>{s[0]}</span><div><i className={String(s[2])} style={{width:`${Number(s[1])*2}%`}}/></div><b>{s[1]}%</b></div>)}</div></div></>}
   {(tab==="Overview"||tab==="Articles")&&<div className="article-table panel"><div className="panel-head"><div><b>STORY PERFORMANCE</b><span>LIVE FROM THE NEWSROOM</span></div><button onClick={()=>setTab("Articles")}>VIEW ALL →</button></div><div className="t-head"><span>STORY</span><span>STATUS</span><span>CHANNELS</span><span>VIEWS</span><span></span></div>{loading?<p className="loading">LOADING NEWSROOM…</p>:articles.slice(0,tab==="Articles"?20:5).map(a=><div className="t-row" key={a.id}><div><b>{a.title}</b><span>{a.school.toUpperCase()} · {a.category.toUpperCase()}</span></div><span className={`status ${a.status}`}>● {a.status}</span><span>{a.channel.split(",").map(c=><i key={c}>{c==="site"?"W":c==="youtube"?"▶":c==="instagram"?"◎":"𝕏"}</i>)}</span><b>{a.views? a.views.toLocaleString():"—"}</b><button>•••</button></div>)}</div>}
   {tab==="Analytics"&&<div className="empty-state"><span>↗</span><h2>Audience intelligence</h2><p>Channel, school, story, and retention reporting is connected and ready.</p><div className="metrics"><Metric label="COMPLETION RATE" value="68.2%" delta="+8.1%"/><Metric label="RETURNING READERS" value="31.4K" delta="+15.3%"/><Metric label="VIDEO STARTS" value="22.8K" delta="+9.6%"/><Metric label="NEWSLETTER CTR" value="14.7%" delta="+2.4%"/></div></div>}
   {!["Overview","Articles","Analytics"].includes(tab)&&<div className="empty-state"><span>✦</span><h2>{tab} control room</h2><p>This desk is connected to the publishing workflow and ready for the next campaign.</p><button className="new">OPEN QUEUE →</button></div>}
  </section>
  {composer&&<div className="modal" role="dialog" aria-modal="true" aria-label="Create story"><form onSubmit={save}><div className="modal-head"><div><span>NEW ASSIGNMENT</span><h2>Build the record.</h2></div><button type="button" onClick={()=>setComposer(false)}>×</button></div><label>HEADLINE<input required value={form.title} onChange={e=>setForm({...form,title:e.target.value})} placeholder="What happened?"/></label><div className="form-row"><label>SCHOOL<input required value={form.school} onChange={e=>setForm({...form,school:e.target.value})} placeholder="University or college"/></label><label>DESK<select value={form.category} onChange={e=>setForm({...form,category:e.target.value})}><option>Campus life</option><option>Investigation</option><option>Video</option><option>Documents</option><option>Culture</option></select></label></div><label>STORY<textarea value={form.body} onChange={e=>setForm({...form,body:e.target.value})} placeholder="Start reporting…"/></label><div className="publish-row"><select value={form.status} onChange={e=>setForm({...form,status:e.target.value})}><option value="draft">Save as draft</option><option value="review">Send to review</option><option value="published">Publish now</option></select><button type="submit" className="new">SAVE STORY →</button></div></form></div>}
 </main>
}
function Metric({label,value,delta}:{label:string;value:string;delta:string}){return <div className="metric"><span>{label}</span><b>{value}</b><em>↗ {delta}</em></div>}
